version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 10
    labels:
      - "type/chore"
      - "status/needs-review"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "type/chore"
      - "status/needs-review"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "type/chore"
      - "status/needs-review"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
