listening-port=3478
tls-listening-port=5349

fingerprint
lt-cred-mech
user=##TURN_USERNAME##:##TURN_PASSWORD##
realm=##TURN_REALM##

listening-ip=0.0.0.0
relay-ip=0.0.0.0
##TURN_EXTERNAL_IP##

min-port=##TURN_MIN_PORT##
max-port=##TURN_MAX_PORT##

no-cli
no-loopback-peers
no-multicast-peers

verbose
log-file=stdout
